### ISSUE TITLE
There is any additional step to configure or setup the stubbbbs ?

### ISSUE THREAD

**Issue by daguitosama** [mcansh/stubbbbbs#8]
I have clone it, installed with `pnpm` and spin it up with `pnpm storybook` and i get a `process not defined` error. This only works with npm install or something else im missing here ?
<img width="1296" alt="Screenshot 2023-04-17 at 15 43 07" src="https://user-images.githubusercontent.com/34744883/232594513-fec47e94-5458-4398-9a18-cc666d621f57.png">

**Comment by mcansh** [comment]
there shouldn't be.. i just cloned this repo again and it worked like a charm

```sh
gh repo clone mcansh/stubbbbbs && \
cd stubbbbbs && \
pnpm import && \
rm package-lock.json && \
pnpm i && \
pnpm storybook
```

**Comment by daguitosama** [comment]
Thanks so much for reporting! I would check that out.

**Comment by daguitosama** [comment]
Thanks so much, it worked out super 👌 
I didn’t know about `pnpm import` 😅

The story examples are awesome! 


<img width="1282" alt="Screenshot 2023-05-02 at 23 55 17" src="https://user-images.githubusercontent.com/34744883/235829992-b79315c1-a6f9-4ca9-86fa-4a4669a96c43.png">
